# Giraph
FROM htaox/giraph-base:1.1.0
MAINTAINER htaox htaox@hotmail.com

ADD files /root/giraph_master_files
RUN chmod 700 /root/giraph_master_files/default_cmd
CMD ["/root/giraph_master_files/default_cmd"]
