#!/bin/bash

env

source /root/faunus_files/configure_faunus.sh

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "MASTER_IP=$IP"

echo "preparing Faunus"
prepare_faunus $IP

echo "starting Hadoop Namenode"
sudo -u hdfs hadoop namenode -format > /dev/null 2>&1
service hadoop-namenode start > /dev/null 2>&1

echo "starting sshd"
/usr/sbin/sshd

echo "starting Faunus Master"

#Spin forever
while true; do sleep 1000; done

# Don't start Faunus yet.  Need to wait for the datanodes to come up.
