#!/bin/bash

env

source /root/faunus_files/configure_faunus.sh

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "MASTER_IP=$IP"

echo "preparing Faunus"
prepare_faunus $IP

echo "starting Hadoop Namenode"
sudo -u hdfs hadoop namenode -format > /dev/null 2>&1
service hadoop-namenode start > /dev/null 2>&1

echo "starting sshd"
/usr/sbin/sshd

echo "starting Faunus Master"

# Hack to update /etc/hosts
# http://stackoverflow.com/questions/19414543/how-can-i-make-etc-hosts-writable-by-root-in-a-docker-container
#ADD your_hosts_file /tmp/hosts
# cp /etc/hosts /etc/hosts.bak
# echo 172.17.0.3 >> /etc/hosts.bak
#RUN mkdir -p -- /lib-override && cp /lib/x86_64-linux-gnu/libnss_files.so.2 /lib-override
#RUN perl -pi -e 's:/etc/hosts:/etc/hosts.bak:g' /lib-override/libnss_files.so.2
#ENV LD_LIBRARY_PATH /lib-override

#Spin forever
while true; do sleep 1000; done

# Don't start Faunus yet.  Need to wait for the datanodes to come up.
