#!/bin/bash

elasticsearch_dirs=$(ls -d elasticsearch*)
dir_list=("$elasticsearch_dirs")

# NOTE: the order matters but this is the right one
for i in ${dir_list[@]}; do
	echo building $i;
	cd $i;
	cat build;
	. build;
	cd ..;
done
