#!/bin/bash

hbase_dirs=$(ls -d hbase*)
dir_list=("$hbase_dirs")

# NOTE: the order matters but this is the right one
for i in ${dir_list[@]}; do
	echo building $i;
	cd $i;
	cat build;
	. build;
	cd ..;
done
