# HBase
FROM htaox/faunus-base:0.4.4
MAINTAINER htaox htaox@hotmail.com

ADD files /root/faunus_master_files
RUN chmod 700 /root/faunus_master_files/default_cmd
CMD ["/root/faunus_master_files/default_cmd"]
