#!/bin/bash

env

source /root/giraph_files/configure_giraph.sh

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "MASTER_IP=$IP"

echo "preparing Giraph"
prepare_giraph $IP

echo "starting Hadoop Namenode"
sudo -u hdfs hadoop namenode -format > /dev/null 2>&1
service hadoop-namenode start > /dev/null 2>&1

echo "starting sshd"
/usr/sbin/sshd

while [ 1 ];
do
	tail -f "${GIRAPH_HOME}/logs"/*.out
        sleep 1
done
